# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
  namespace: verrazzano-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - image: CONSOLE_DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          name: console
          ports:
            - containerPort: 8000
          env:
            - name: VZ_API_URL
              value: VZ_API_URL_VALUE
            - name: VZ_AUTH
              value: "false"
---
kind: Service
apiVersion: v1
metadata:
  name: console
  namespace: verrazzano-system
spec:
  type: NodePort
  selector:
    app: console
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30100
