# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

kind: Service
apiVersion: v1
metadata:
  name: verrazzano-operator
  namespace: verrazzano-system
spec:
  type: NodePort
  selector:
    app: verrazzano-operator
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 3456
      nodePort: 30200
